site_name: Schedula

repo_name: "2022.2-Schedula"
repo_url: "https://github.com/fga-eps-mds/2022-2-Schedula-Doc"

theme:
  name: material
  language: "pt"
  logo: "global/assets/favicon.ico"
  favicon: "global/assets/favicon.ico"
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Gestão de Projeto:
      - Estrutura Analítica do Projeto: gestao_de_projeto/estrutura_analitica_do_projeto.md
      - Plano de Gerenciamento de Riscos: gestao_de_projeto/gestao_de_risco.md
    - Estrutura Analítica do Projeto: gestao_de_projeto/estrutura_analitica_do_projeto.md
  - Modelagem:
    - Backlog: modelagem/backlog.md
  - Visão de Produto:
    - Lean Inception: visao_de_produto/lean_inception.md
  - Planejamento:
    - Metodologia: planejamento/metodologias.md
    - Planejamento de Comunicação: planejamento/comunicacao.md
  - Guia de Contribuição: guia_de_contribuicao.md
dev_addr: "0.0.0.0:8000"
