site_name: Schedula

repo_name: "2022.2-Schedula"
repo_url: "https://github.com/fga-eps-mds/2022-2-Schedula-Doc"

theme:
  name: material
  language: "pt"
  logo: "global/assets/favicon.ico"
  favicon: "global/assets/favicon.ico"
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Planejamento:
      - Metodologia: planejamento/metodologias.md
      - Planejamento de Comunicação: planejamento/comunicacao.md
      - Quadro de conhecimentos: planejamento/conhecimento.md
  - Visão de Produto:
      - Lean Inception: visao_de_produto/lean_inception.md
  - Modelagem:
      - Backlog: modelagem/backlog.md
  - Gestão de Projeto:
    - Documento de Arquitetura: gestao_de_projeto/documento_arquitetura.md
    - Estrutura Analítica do Projeto: gestao_de_projeto/estrutura_analitica_do_projeto.md
    - Plano de Custos: gestao_de_projeto/plano_de_custo.md
    - Plano de Gerenciamento de Riscos: gestao_de_projeto/gestao_de_risco.md
  - Sprints:
    - Sprint 0: sprints/sprint-0.md
    - Sprint 1: sprints/sprint-1.md
    - Sprint 2: sprints/sprint-2.md
    - Sprint 3: sprints/sprint-3.md
  - Treinamento: treinamento.md
  - Guia de Contribuição: guia_de_contribuicao.md
dev_addr: "0.0.0.0:8000"
